uploads = []
outputs = []

[[generated]]
id = "7Cf-m1gqooQ_y3GEHcAzY"
uri = "file://artifacts/shaadi-app/src/assets/images/profile1.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "GVyDO8e_h3dMX8dmQxG39"
uri = "file://artifacts/shaadi-app/src/assets/images/profile2.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "NaPmsA_MZuJQLxswVn793"
uri = "file://artifacts/shaadi-app/src/assets/images/profile3.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "HwWcxAbKSnPnzABaUkQzA"
uri = "file://artifacts/shaadi-app/src/assets/images/profile4.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "VSOxvk0WSxrdkzsDZjwj1"
uri = "file://artifacts/shaadi-app/src/assets/images/profile5.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "qTiH6ObgNRYExUpDge93s"
uri = "file://artifacts/shaadi-app/src/assets/images/profile6.png"
type = "image"
title = "Professional headshot Indian woman"

[[generated]]
id = "Y_uc6G644jm2-bGLXUR3o"
uri = "file://artifacts/shaadi-app/src/assets/images/hero-bg.png"
type = "image"
title = "Indian wedding hero scene"

[[generated]]
id = "3qhdv_tseBQEHxgE6UpmQ"
uri = "file://artifacts/shaadi-app/src/assets/images/featured1.png"
type = "image"
title = "Indian woman portrait"

[[generated]]
id = "Yj9MGmlBmndQHMI9I8PkD"
uri = "file://artifacts/shaadi-app/src/assets/images/featured2.png"
type = "image"
title = "Indian woman portrait"

[[generated]]
id = "B57d-2fCqyAziHQrcCLDW"
uri = "file://artifacts/shaadi-app/src/assets/images/featured3.png"
type = "image"
title = "Indian woman portrait"

[[generated]]
id = "eLOeRa8dEscSvJJGOKz9L"
uri = "file://artifacts/shaadi-app/src/assets/images/featured4.png"
type = "image"
title = "Indian man portrait"

[[generated]]
id = "bqx0qjuNG_J_DICoFiAtS"
uri = "file://artifacts/shaadi-app/src/assets/images/featured5.png"
type = "image"
title = "Indian man portrait"

[[generated]]
id = "AjkWUToZZlr5Z2W4-Wf0A"
uri = "file://artifacts/shaadi-app/src/assets/images/featured6.png"
type = "image"
title = "Indian man portrait"

[[generated]]
id = "Xa8iset6rIiAURBZgXB8r"
uri = "file://artifacts/shaadi-app/src/assets/images/couple1.png"
type = "image"
title = "Happy Indian couple"

[[generated]]
id = "1yCTIOYMFzxiVTJAIGqb9"
uri = "file://artifacts/shaadi-app/src/assets/images/couple2.png"
type = "image"
title = "Happy Indian couple"

[[generated]]
id = "lc3m8XL2GB2FRUblCIvih"
uri = "file://artifacts/shaadi-app/src/assets/images/couple3.png"
type = "image"
title = "Happy Indian couple"
